	<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>NG</title>
	<link href="CSS/bootstrap.min.css" rel="stylesheet">
	<link href="CSS/bootstrap-theme.min.css" rel="stylesheet">
	<link href="CSS/mystyle.css" rel="stylesheet">
	<link href="CSS/font-awesome.min.css" rel="stylesheet">
	<link href="CSS/bootstrap-social.css" rel="stylesheet"> 	

</head>
<body>

<!--=============================================================== NAVBAR =============================================================== -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="master.html">NavalGohil</a>
			<button type="button" class="navbar-toggle collapsed"
				data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-control="navbar" >
				<span class="sr-only">Toggle Navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li  class="active"><a href="master.html"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home</a></li>
				<li><a onclick="window.open('https://html-online.com/editor/');" target="_blank">Editor</a></li>
				<li><a href="contact.html">Contact</a></li>					
			</ul>
		 </div>
	</div> <!-- container -->
</nav>

<!--=============================================================== HEADER =============================================================== -->

<!--=============================================================== MAIN BODY =============================================================== -->
<div class="container">

<h1>Exception Concepts</h1>
<p><a href="https://www.geeksforgeeks.org/exceptions-in-java/">https://www.geeksforgeeks.org/exceptions-in-java/</a></p>
<p><a href="https://www.geeksforgeeks.org/types-of-exception-in-java-with-examples/">https://www.geeksforgeeks.org/types-of-exception-in-java-with-examples/</a></p>
<p><strong>What is an Exception?</strong></p>
<p>An exception is an unwanted or unexpected event, which occurs during the execution of a program i.e at run time, that disrupts the normal flow of the program&rsquo;s instructions.</p>
<p><strong>Exception Hierarchy</strong></p>
<p>All exception and errors types are sub classes of class&nbsp;<strong>Throwable</strong>, which is base class of hierarchy.One branch is headed by&nbsp;<strong>Exception</strong>. This class is used for exceptional conditions that user programs should catch. NullPointerException is an example of such an exception.Another branch,<strong>Error</strong>&nbsp;are used by the Java run-time system(<a href="https://www.geeksforgeeks.org/jvm-works-jvm-architecture/">JVM</a>) to indicate errors having to do with the run-time environment itself(JRE). StackOverflowError is an example of such an error.</p>
<div class="dp-highlighter">
<h3><strong>What is the difference between Error and Exception?</strong></h3>
<p><strong>Error vs Exception</strong></p>
<p><strong>Error:&nbsp;</strong>An Error indicates serious problem that a reasonable application should not try to catch.<br /><strong>Exception:&nbsp;</strong>Exception indicates conditions that a reasonable application might try to catch.</p>
<p>An error is an irrecoverable condition occurring at runtime. Such as OutOfMemory error. These JVM errors you cannot repair them at runtime. Though error can be caught in the catch block but the execution of application will come to a halt and is not recoverable.</p>
<p>While exceptions are conditions that occur because of bad input or human error etc. e.g. FileNotFoundException will be thrown if the specified file does not exist. Or a NullPointerException will take place if you try using a null reference. In most of the cases it is possible to recover from an exception (probably by giving the user feedback for entering proper values etc.</p>
<h3><strong>How can you handle Java exceptions?</strong></h3>
<p>There are five keywords used to handle exceptions in Java:&nbsp;</p>
<ol>
<li>try</li>
<li>catch</li>
<li>finally</li>
<li>throw</li>
<li>throws</li>
</ol>
<h3><strong>What are the differences between Checked Exception and Unchecked Exception?</strong></h3>
<p><strong>For checked vs unchecked exception, see&nbsp;<a href="https://www.geeksforgeeks.org/checked-vs-unchecked-exceptions-in-java/">Checked vs Unchecked Exceptions</a></strong></p>
<p><strong><a href="https://www.geeksforgeeks.org/checked-vs-unchecked-exceptions-in-java/">https://www.geeksforgeeks.org/checked-vs-unchecked-exceptions-in-java/</a></strong></p>
<h4><strong>Checked Exception</strong></h4>
<ul>
<li>The classes that extend Throwable class except RuntimeException and Error are known as checked exceptions.&nbsp;</li>
<li>Checked exceptions are checked at compile-time.</li>
<li>Example: IOException, SQLException etc.</li>
</ul>
<h4><strong>Unchecked Exception</strong></h4>
<ul>
<li>The classes that extend RuntimeException are known as unchecked exceptions.&nbsp;</li>
<li>Unchecked exceptions are not checked at compile-time.</li>
<li>Example: ArithmeticException, NullPointerException etc.</li>
</ul>
<h3><strong>What purpose do the keywords final, finally, and finalize fulfill?&nbsp;</strong></h3>
<h4><strong>Final:</strong></h4>
<p>Final is used to apply restrictions on class, method, and variable. A final class can&rsquo;t be inherited, final method can&rsquo;t be overridden and final variable value can&rsquo;t be changed. Let&rsquo;s take a look at the example below to understand it better.</p>
<div>
<div id="highlighter_529202" class="syntaxhighlighter  java">
<table border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td class="code">
<div class="container">
<div class="line number1 index0 alt2"><code class="java keyword">class</code>&nbsp;<code class="java plain">FinalVarExample {</code></div>
<div class="line number2 index1 alt1"><code class="java keyword">public</code>&nbsp;<code class="java keyword">static</code>&nbsp;<code class="java keyword">void</code>&nbsp;<code class="java plain">main( String args[])</code></div>
<div class="line number3 index2 alt2"><code class="java plain">{</code></div>
<div class="line number4 index3 alt1"><code class="java keyword">final</code>&nbsp;<code class="java keyword">int</code>&nbsp;<code class="java plain">a=</code><code class="java value">10</code><code class="java plain">;&nbsp;&nbsp;&nbsp;</code><code class="java comments">// Final variable</code></div>
<div class="line number5 index4 alt2"><code class="java plain">a=</code><code class="java value">50</code><code class="java plain">;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="java comments">//Error as value can't be changed</code></div>
<div class="line number6 index5 alt1"><code class="java plain">}</code></div>
</div>
</td>
</tr>
</tbody>
</table>
</div>
</div>
<h4><strong>Finally</strong></h4>
<p>Finally is used to place important code, it will be executed whether the exception is handled or not. Let&rsquo;s take a look at the example below to understand it better.</p>
<div>
<div id="highlighter_863308" class="syntaxhighlighter  java">
<table style="width: 387px;" border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td class="code" style="width: 383.333px;">
<div class="container">
<div class="line number1 index0 alt2"><code class="java keyword">class</code>&nbsp;<code class="java plain">FinallyExample {</code></div>
<div class="line number2 index1 alt1"><code class="java keyword">public</code>&nbsp;<code class="java keyword">static</code>&nbsp;<code class="java keyword">void</code>&nbsp;<code class="java plain">main(String args[]){</code></div>
<div class="line number3 index2 alt2"><code class="java keyword">try</code>&nbsp;<code class="java plain">{</code></div>
<div class="line number4 index3 alt1"><code class="java keyword">int</code>&nbsp;<code class="java plain">x=</code><code class="java value">100</code><code class="java plain">;</code></div>
<div class="line number5 index4 alt2"><code class="java plain">}</code></div>
<div class="line number6 index5 alt1"><code class="java keyword">catch</code><code class="java plain">(Exception e) {</code></div>
<div class="line number7 index6 alt2"><code class="java plain">System.out.println(e);</code></div>
<div class="line number8 index7 alt1"><code class="java plain">}</code></div>
<div class="line number9 index8 alt2"><code class="java keyword">finally</code>&nbsp;<code class="java plain">{</code></div>
<div class="line number10 index9 alt1"><code class="java plain">System.out.println(</code><code class="java string">"finally block is executing"</code><code class="java plain">);}</code></div>
<div class="line number11 index10 alt2"><code class="java plain">}}</code></div>
<div class="line number12 index11 alt1"><code class="java plain">}</code></div>
</div>
</td>
</tr>
</tbody>
</table>
<h4><strong>Finalize</strong></h4>
<p>Finalize is used to perform clean up processing just before the object is garbage collected. Let&rsquo;s take a look at the example below to understand it better.</p>
<div>
<div id="highlighter_35078" class="syntaxhighlighter  java">
<table border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td class="code">
<div class="container">
<div class="line number1 index0 alt2"><code class="java keyword">class</code>&nbsp;<code class="java plain">FinalizeExample {</code></div>
<div class="line number2 index1 alt1"><code class="java keyword">public</code>&nbsp;<code class="java keyword">void</code>&nbsp;<code class="java plain">finalize() {</code></div>
<div class="line number3 index2 alt2"><code class="java plain">System.out.println(</code><code class="java string">"Finalize is called"</code><code class="java plain">);</code></div>
<div class="line number4 index3 alt1"><code class="java plain">}</code></div>
<div class="line number5 index4 alt2"><code class="java keyword">public</code>&nbsp;<code class="java keyword">static</code>&nbsp;<code class="java keyword">void</code>&nbsp;<code class="java plain">main(String args[])</code></div>
<div class="line number6 index5 alt1"><code class="java plain">{</code></div>
<div class="line number7 index6 alt2"><code class="java plain">FinalizeExample f1=</code><code class="java keyword">new</code>&nbsp;<code class="java plain">FinalizeExample();</code></div>
<div class="line number8 index7 alt1"><code class="java plain">FinalizeExample f2=</code><code class="java keyword">new</code>&nbsp;<code class="java plain">FinalizeExample();</code></div>
<div class="line number9 index8 alt2"><code class="java plain">f1= NULL;</code></div>
<div class="line number10 index9 alt1"><code class="java plain">f2=NULL;</code></div>
<div class="line number11 index10 alt2"><code class="java plain">System.gc();</code></div>
<div class="line number12 index11 alt1"><code class="java plain">}</code></div>
<div class="line number13 index12 alt2"><code class="java plain">}</code></div>
</div>
</td>
</tr>
</tbody>
</table>
<h3><strong>What are the differences between throw and throws?&nbsp;</strong></h3>
<p><strong><a href="https://www.geeksforgeeks.org/throw-throws-java/">https://www.geeksforgeeks.org/throw-throws-java/</a></strong></p>
<table border="1">
<tbody>
<tr>
<td><strong>throw keyword</strong></td>
<td><strong>throws keyword</strong></td>
</tr>
<tr>
<td>Throw is used to explicitly throw an exception.</td>
<td>Throws is used to declare an exception.</td>
</tr>
<tr>
<td>Checked exceptions can not be propagated with throw only.</td>
<td>Checked exception can be propagated with throws.</td>
</tr>
<tr>
<td>Throw is followed by an instance.</td>
<td>Throws is followed by class.</td>
</tr>
<tr>
<td>Throw is used within the method.</td>
<td>Throws is used with the method signature.</td>
</tr>
<tr>
<td>You cannot throw multiple exception</td>
<td>You can declare multiple exception e.g. public void method()throws IOException,SQLException.</td>
</tr>
</tbody>
</table>
<div class="dp-highlighter">throw keyword is used to throw Exception from any method or static block whereas throws is used to indicate that which Exception can possibly be thrown by this method<br />If any method throws checked Exception, then caller can either handle this exception(using try catch block )or can re throw it by declaring another &lsquo;throws&rsquo; clause in method declaration.<br />throw clause can be used in any part of code where you feel a specific exception needs to be thrown to the calling method<br />E.g.<br /><strong>throw</strong><br />throw new Exception(&ldquo;You have some exception&rdquo;)<br />throw new IOException(&ldquo;Connection failed!!&rdquo;)<br /><strong>throws</strong><br />throws IOException, NullPointerException, ArithmeticException</div>
<div class="dp-highlighter">
<p><strong>Important points to remember about throws keyword:</strong></p>
<ul>
<li>throws keyword is required only for checked exception and usage of throws keyword for unchecked exception is meaningless.</li>
<li>throws keyword is required only to convince compiler and usage of throws keyword does not prevent abnormal termination of program.</li>
<li>By the help of throws keyword we can provide information to the caller of the method about the exception.</li>
</ul>
</div>
<div class="dp-highlighter">
<h3><strong>How to create a custom Exception?</strong></h3>
<p>To create you own exception extend the Exception class or any of its subclasses.</p>
<ul>
<li>class New1Exception extends Exception { } &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; // this will create Checked Exception</li>
<li>class NewException extends IOException { } &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; // this will create Checked exception</li>
<li>class NewException extends NullPonterExcpetion { } &nbsp;// this will create UnChecked exception</li>
</ul>
<h3><strong>What are the important methods of Java Exception Class?</strong></h3>
<p>Exception and all of it&rsquo;s subclasses doesn&rsquo;t provide any specific methods and all of the methods are defined in the base class Throwable.</p>
<ol>
<li><strong>String getMessage()</strong>&nbsp;&ndash; This method returns the message String of Throwable and the message can be provided while creating the exception through it&rsquo;s constructor.</li>
<li><strong>String getLocalizedMessage(</strong>) &ndash; This method is provided so that subclasses can override it to provide locale specific message to the calling program. Throwable class implementation of this method simply use&nbsp;getMessage()&nbsp;method to return the exception message.</li>
<li><strong>Synchronized Throwable getCause()</strong>&nbsp;&ndash; This method returns the cause of the exception or null id the cause is unknown.</li>
<li><strong>String toString()</strong>&nbsp;&ndash; This method returns the information about Throwable in String format, the returned String contains the name of Throwable class and localized message.</li>
<li><strong>void printStackTrace()</strong>&nbsp;&ndash; This method prints the stack trace information to the standard error stream, this method is overloaded and we can pass PrintStream or PrintWriter as an argument to write the stack trace information to the file or stream.</li>
</ol>
</div>
<h3><strong>What is a finally block? Is there a&nbsp;case when finally will not execute?</strong></h3>
<p>Finally block is a block which always executes a set of statements. It is always associated with a try block regardless of any exception that occurs or not.&nbsp;<br />Yes, finally will not be executed if the program exits either by&nbsp;calling System.exit() or by causing a fatal error that causes the process to abort.</p>
<h3><strong>Can we write multiple catch blocks under single try block?&nbsp;</strong></h3>
<p>Yes we can have multiple catch blocks under single try block but the approach should be from specific to general. Let&rsquo;s understand this with a programmatic example.</p>
<div>
<div id="highlighter_752943" class="syntaxhighlighter  java">
<table border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td class="code">
<div class="container">
<div class="line number1 index0 alt2"><code class="java keyword">public</code>&nbsp;<code class="java keyword">class</code>&nbsp;<code class="java plain">Example {</code></div>
<div class="line number2 index1 alt1"><code class="java keyword">public</code>&nbsp;<code class="java keyword">static</code>&nbsp;<code class="java keyword">void</code>&nbsp;<code class="java plain">main(String args[]) {</code></div>
<div class="line number3 index2 alt2"><code class="java keyword">try</code>&nbsp;<code class="java plain">{</code></div>
<div class="line number4 index3 alt1"><code class="java keyword">int</code>&nbsp;<code class="java plain">a[]=&nbsp;</code><code class="java keyword">new</code>&nbsp;<code class="java keyword">int</code><code class="java plain">[</code><code class="java value">10</code><code class="java plain">];</code></div>
<div class="line number5 index4 alt2"><code class="java plain">a[</code><code class="java value">10</code><code class="java plain">]=&nbsp;</code><code class="java value">10</code><code class="java plain">/</code><code class="java value">0</code><code class="java plain">;</code></div>
<div class="line number6 index5 alt1"><code class="java plain">}</code></div>
<div class="line number7 index6 alt2"><code class="java keyword">catch</code><code class="java plain">(ArithmeticException e)</code></div>
<div class="line number8 index7 alt1"><code class="java plain">{</code></div>
<div class="line number9 index8 alt2"><code class="java plain">System.out.println(</code><code class="java string">"Arithmetic exception in first catch block"</code><code class="java plain">);</code></div>
<div class="line number10 index9 alt1"><code class="java plain">}</code></div>
<div class="line number11 index10 alt2"><code class="java keyword">catch</code><code class="java plain">(ArrayIndexOutOfBoundsException e)</code></div>
<div class="line number12 index11 alt1"><code class="java plain">{</code></div>
<div class="line number13 index12 alt2"><code class="java plain">System.out.println(</code><code class="java string">"Array index out of bounds in second catch block"</code><code class="java plain">);</code></div>
<div class="line number14 index13 alt1"><code class="java plain">}</code></div>
<div class="line number15 index14 alt2"><code class="java keyword">catch</code><code class="java plain">(Exception e)</code></div>
<div class="line number16 index15 alt1"><code class="java plain">{</code></div>
<div class="line number17 index16 alt2"><code class="java plain">System.out.println(</code><code class="java string">"Any exception in third catch block"</code><code class="java plain">);</code></div>
<div class="line number18 index17 alt1"><code class="java plain">}</code></div>
<div class="line number19 index18 alt2"><code class="java plain">}</code></div>
</div>
</td>
</tr>
</tbody>
</table>
</div>
</div>
<h3><strong>What are the important methods of Java Exception Class?</strong></h3>
<p>Methods are defined in the base class Throwable. Some of the important methods of Java exception class are stated below.&nbsp;</p>
<ol>
<li><strong>String getMessage()</strong>&nbsp;&ndash; This method returns the message String about the exception. The message can be provided through its constructor.</li>
<li><strong>public StackTraceElement[] getStackTrace() &ndash;&nbsp;</strong>This method returns an array containing each element on the stack trace. The element at index 0 represents the top of the call stack whereas the last element in the array represents the method at the bottom of the call stack.</li>
<li>
<p><strong>Synchronized Throwable getCause()</strong>&nbsp;&ndash; This method returns the cause of the exception or null id as represented by a Throwable object.</p>
</li>
<li><strong>String toString()</strong>&nbsp;&ndash; This method returns the information in String format. The returned String contains the name of Throwable class and localized message.</li>
<li><strong>void printStackTrace()</strong>&nbsp;&ndash; This method prints the stack trace information to the standard error stream.&nbsp;</li>
</ol>
<h3><strong>What is OutOfMemoryError in Java?</strong></h3>
<p>OutOfMemoryError is the subclass of java.lang.Error which generally occurs when our JVM runs out of memory.</p>
<p><strong>What will happen if you put System.exit(0) on try or catch block? Will finally block execute?</strong><br /><br />By Calling System.exit(0) in try or catch block, we can skip the finally block. System.exit(int) method can throw a SecurityException. If Sysytem.exit(0) exits the JVM without throwing that exception then finally block will not execute. But, if System.exit(0) does throw security exception then finally block will be executed.</p>
<h1>Chained Exceptions in Java</h1>
<p><a href="https://www.geeksforgeeks.org/chained-exceptions-java/">https://www.geeksforgeeks.org/chained-exceptions-java/</a></p>
<p>Chained Exceptions allows to relate one exception with another exception, i.e one exception describes cause of another exception. For example, consider a situation in which a method throws an ArithmeticException because of an attempt to divide by zero but the actual cause of exception was an I/O error which caused the divisor to be zero. The method will throw only ArithmeticException to the caller. So the caller would not come to know about the actual cause of exception. Chained Exception is used in such type of situations.</p>
<h1>Types of Exception in Java with Examples</h1>
<p><a href="https://www.geeksforgeeks.org/types-of-exception-in-java-with-examples/">https://www.geeksforgeeks.org/types-of-exception-in-java-with-examples/</a></p>
<p>Java defines several types of exceptions that relate to its various class libraries. Java also allows users to define their own exceptions.</p>
<p><a href="https://www.geeksforgeeks.org/built-exceptions-java-examples/"><strong>Built-in Exceptions</strong></a></p>
<p>Built-in exceptions are the exceptions which are available in Java libraries. These exceptions are suitable to explain certain error situations. Below is the list of important built-in exceptions in Java.</p>
<ol>
<li><strong>ArithmeticException</strong><br />It is thrown when an exceptional condition has occurred in an arithmetic operation.</li>
<li><strong>ArrayIndexOutOfBoundsException<br /></strong>It is thrown to indicate that an array has been accessed with an illegal index. The index is either negative or greater than or equal to the size of the array.</li>
<li><strong>ClassNotFoundException<br /></strong>This Exception is raised when we try to access a class whose definition is not found</li>
<li><strong>FileNotFoundException<br /></strong>This Exception is raised when a file is not accessible or does not open.</li>
<li><strong>IOException<br /></strong>It is thrown when an input-output operation failed or interrupted</li>
<li><strong>InterruptedException<br /></strong>It is thrown when a thread is waiting , sleeping , or doing some processing , and it is interrupted.</li>
<li><strong>NoSuchFieldException<br /></strong>It is thrown when a class does not contain the field (or variable) specified</li>
<li><strong>NoSuchMethodException<br /></strong>It is thrown when accessing a method which is not found.</li>
<li><strong>NullPointerException<br /></strong>This exception is raised when referring to the members of a null object. Null represents nothing</li>
<li><strong>NumberFormatException<br /></strong>This exception is raised when a method could not convert a string into a numeric format.</li>
<li><strong>RuntimeException<br /></strong>This represents any exception which occurs during runtime.</li>
<li><strong>StringIndexOutOfBoundsException<br /></strong>It is thrown by String class methods to indicate that an index is either negative than the size of the string</li>
</ol>
<p><strong>User-Defined Exceptions</strong></p>
<p>Sometimes, the built-in exceptions in Java are not able to describe a certain situation. In such cases, user can also create exceptions which are called &lsquo;user-defined Exceptions&rsquo;.<br />Following steps are followed for the creation of user-defined Exception.</p>
<ul>
<li>The user should create an exception class as a subclass of Exception class. Since all the exceptions are subclasses of Exception class, the user should also make his class a subclass of it. This is done as:</li>
</ul>
<p>class MyException extends Exception</p>
<ul>
<li>We can write a default constructor in his own exception class.</li>
</ul>
<p>MyException(){}</p>
<ul>
<li>We can also create a parameterized constructor with a string as a parameter.<br />We can use this to store exception details. We can call super class(Exception) constructor from this and send the string there.</li>
</ul>
<p>MyException(String str)</p>
<p>{</p>
<p>&nbsp;&nbsp; super(str);</p>
<p>}</p>
<ul>
<li>To raise exception of user-defined type, we need to create an object to his exception class and throw it using throw clause, as:</li>
</ul>
<p>MyException me = new MyException(&ldquo;Exception details&rdquo;);</p>
<p>throw me;</p>
<ul>
<li>The following program illustrates how to create own exception class MyException.</li>
<li>Details of account numbers, customer names, and balance amounts are taken in the form of three arrays.</li>
<li>In main() method, the details are displayed using a for-loop. At this time, check is done if in any account the balance amount is less than the minimum balance amount to be ept in the account.</li>
<li>If it is so, then MyException is raised and a message is displayed &ldquo;Balance amount is less&rdquo;.</li>
</ul>
<h1>Catching base and derived classes as exceptions</h1>
<p><a href="https://www.geeksforgeeks.org/g-fact-60/">https://www.geeksforgeeks.org/g-fact-60/</a></p>
<p><strong>Exception Handling &ndash; catching base and derived classes as exceptions:</strong></p>
<p>If both base and derived classes are caught as exceptions then catch block of derived class must appear before the base class.</p>
<p>In Java, catching a base class exception before derived is not allowed by the compiler itself.</p>
<p>For example, following Java code fails in compilation with error message&nbsp;<em>&ldquo;exception Derived has already been caught&rdquo;</em></p>
<p>//filename Main.java</p>
<p>class Base extends Exception {}</p>
<p>class Derived extends Base&nbsp; {}</p>
<p>public class Main {</p>
<p>&nbsp;&nbsp;public static void main(String args[]) {</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;try {</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw new Derived();</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;}</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;catch(Base b) {}</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;catch(Derived d) {}</p>
<p>&nbsp;&nbsp;}</p>
<p>}</p>
</div>
</div>
</div>
</div>
</div>


</div> <!-- B CONTAINER -->             

  
<!--=============================================================== FOOTER =============================================================== -->
<div class="footer row-footer">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				
				<p align="Left"> <b>@Copyright 2019 Naval Gohil</b></p>
			</div>
		</div> <!-- F ROW 1 -->
	</div> <!-- F CONTAINER -->
</div> <!-- FOOTER -->

<script  src="JS/jquery-1.11.3.min.js" ></script>
<script  src="JS/bootstrap.min.js" ></script>
<script  src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script> 
<script type="text/javascript">
           $(document).ready(function() {
				$('#example').DataTable({
					pagingType: 'full_numbers',
				});
			});
			document.addEventListener('keydown', function() {
			  if (event.keyCode == 123) {
				alert("This function has been disabled to prevent you from stealing my code!");
				return false;
			  } else if (event.ctrlKey && event.shiftKey && event.keyCode == 73) {
				alert("This function has been disabled to prevent you from stealing my code!");
				return false;
			  } else if (event.ctrlKey && event.keyCode == 85) {
				alert("This function has been disabled to prevent you from stealing my code!");
				return false;
			  }
			}, false);

			if (document.addEventListener) {
			  document.addEventListener('contextmenu', function(e) {
				alert("This function has been disabled to prevent you from stealing my code!");
				e.preventDefault();
			  }, false);
			} else {
			  document.attachEvent('oncontextmenu', function() {
				alert("This function has been disabled to prevent you from stealing my code!");
				window.event.returnValue = false;
			  });
			}
</script>


</body>
</html>
